#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"

  block compile pipenv
  mkdir -p "$shome/bin"
  ln -nfs "$(pipenv run which cli4)" "$shome/bin/"

  local url_download
  case "${DISTRIB_ID}" in
    Darwin)
      curl -s "$(curl -s https://dl.equinox.io/cloudflare/cloudflared/stable/archive | grep "${CLOUDFLARED_VERSION}-darwin-amd64.tar.gz" | cut -d'"' -f2)"
      ;;
    *)
      curl -s "$(curl -s https://dl.equinox.io/cloudflare/cloudflared/stable/archive | grep "${CLOUDFLARED_VERSION}-linux-amd64.tar.gz" | cut -d'"' -f2)"
      ;;
  esac | tar xzC "$shome/bin"
}

main "$@"
