#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_cloudflare="$(cli4 --version 2>/dev/null | awk '{print $NF}' || true)"
  jq -n --arg cloudflare "$ver_cloudflare" '{cloudflare: $cloudflare}'
}

version "$@"
